$('#logo').mouseleave(function(){
  $('.popUpBox').show();
  });
  $('.popUpBox').click(function(){
      $('.popUpBox').hide();
  });
  $('.popupClose').click(function(){
      $('.popUpBox').hide();
  });
